### PR TITLE
Update to Help Options

### PR DESCRIPTION
**Pull request by Charles1992Sail**
Updated to add:

1) "Validate -options" and all of the arguments.

2) Under "Generate -options" between "GenerationTimestamp (-gt)" and "Verbosity (-V)"        

    DeleteManifestDirIfPresent (-D)           If set to true, we will delete any previous manifest
                                              directories that are already present in the
                                              ManifestDirPath without asking the user for
                                              confirmation. The new manifest directory will then
                                              be created at this location and the generated SBOM
                                              will be stored there.

### CODE REVIEW

**Comment by Charles1992Sail** [comment]
@microsoft-github-policy-service agree

**Comment by JamieMagee** [comment]
Thank you for the PR.

Interestingly, we do have [a workflow to update the docs automatically][1], but it [appears to have been manually disabled][2]

[1]: https://github.com/microsoft/sbom-tool/blob/main/.github/workflows/gen-docs.yml
[2]: https://github.com/microsoft/sbom-tool/actions/workflows/gen-docs.yml

**Comment by JamieMagee** [comment]
@sebasgomez238 message me to let me know it's disabled because of #32. In the long-term, I would like to get the automation working, but in the short-term this is great!

**Review by JamieMagee — APPROVED** [review]

**Comment by Charles1992Sail** [comment]
Thanks!  That fix was quick!  Bugs like https://github.com/microsoft/sbom-tool/issues/32 will do it for sure.

**Pull request merged**
